import type { Metadata } from "next";
import {Oswald,Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";


const oswald = Oswald({
  subsets: ['latin'],
  display: 'swap', 
  variable: '--font-oswald', 
})
const inter = Inter({
  subsets: ['latin'],
  display: 'swap', 
  variable: '--font-inter', 
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={` ${oswald.variable} ${inter.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar></Navbar>
        {children}
        </body>
    </html>
  );
}
